/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import DAO.HoaDon;
import Excel.InHoaDon1;
import datechooser.events.SelectionChangedEvent;
import Model.*;
import java.awt.Point;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import DAO.Reposystory_BanHang;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VIETTECH88
 */
public class ViewHoaDon extends javax.swing.JPanel {

    private int checkThoiGianTimKiem = -1;
    private final HoaDon hoaDon;
    private Reposystory_BanHang repo = new Reposystory_BanHang();
    private DefaultTableModel mol = new DefaultTableModel();
    private int index = 0;

    /**
     * Creates new form HoaDon
     */
    public ViewHoaDon() {
        initComponents();
        hoaDon = new HoaDon();
        this.filltable(hoaDon.danhSachHoaDon());
        lblSLuongHoaDon.setText(String.valueOf(tblHoaDon.getRowCount()));
        dateDialog.setModal(true);
        danhSachCbo();
        
        
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentShown(java.awt.event.ComponentEvent evt) {
            capNhatLaiBang();
        }
    });
    }

    void capNhatLaiBang(){
        this.filltable(hoaDon.danhSachHoaDon());
        lblSLuongHoaDon.setText(String.valueOf(tblHoaDon.getRowCount()));
    }
    
    private void filltable(ArrayList<ModelHoaDon> list) {
        mol = (DefaultTableModel) tblHoaDon.getModel();
        mol.setRowCount(0);
        for (ModelHoaDon x : list) {
            mol.addRow(x.toDataRow());
        }
    }

    private void filltableHDCT(ArrayList<ModelHoaDonChiTiet> list) {
        mol = (DefaultTableModel) tblHoaDonChiTiet.getModel();
        mol.setRowCount(0);
        for (ModelHoaDonChiTiet x : list) {
            mol.addRow(x.toDataRow1());
        }
    }

    private void danhSachCbo() {
        cboDonGia.removeAllItems();
        cboTrangThai.removeAllItems();
        cboDonGia.addItem("Tất cả");
        cboDonGia.addItem("Dưới 1 triệu");
        cboDonGia.addItem("1 đến 5triệu");
        cboDonGia.addItem("5 đến 10 triệu");
        cboDonGia.addItem("trên 10 triệu");
        cboTrangThai.addItem("Tất cả");
        cboTrangThai.addItem("Đã thanh toán");
        cboTrangThai.addItem("Chưa thanh toán");
    }

    private ModelHoaDon readform() {
        Boolean trangThai = null;
            Integer donGiaA;
        Integer donGiaB;
        String ngayBatDau = txtThoiGianBatDau.getText().trim();
        String ngayKetThuc = txtThoiGianKetThuc.getText().trim();
        if (ngayBatDau.isBlank()) {
            ngayBatDau = null;
        }

        if (ngayKetThuc.isBlank()) {
            ngayKetThuc = null;
        }

        if (cboTrangThai.getSelectedItem().equals("Đã thanh toán")) {
            trangThai = true;
        } else if (cboTrangThai.getSelectedItem().equals("Chưa thanh toán")) {
            trangThai = false;
        }

        if (cboDonGia.getSelectedItem().equals("Dưới 1 triệu")) {
            donGiaA = 0;
            donGiaB = 1000000;
        } else if (cboDonGia.getSelectedItem().equals("1 đến 5triệu")) {
            donGiaA = 1000000;
            donGiaB = 5000000;
        } else if (cboDonGia.getSelectedItem().equals("5 đến 10 triệu")) {
            donGiaA = 5000000;
            donGiaB = 10000000;
        } else if (cboDonGia.getSelectedItem().equals("trên 10 triệu")) {
            donGiaA = 10000000;
            donGiaB = 999999999;
        } else {
            donGiaA = null;
            donGiaB = null;
        }
        return new ModelHoaDon(ngayBatDau, donGiaA, trangThai, ngayKetThuc, donGiaB);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateDialog = new javax.swing.JDialog();
        thoiGianBatDau = new datechooser.beans.DateChooserPanel();
        hoaDonChiTiet = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_MaHoaDon = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_NgayMuaHang = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_TongTien = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_GiaGiam = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_GiaSauGiam = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_TrangThai = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_MaNhanVien = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_TenNhanVien = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txt_TenKhachHang = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txt_SoDienThoai = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txt_MaKhuyenMai = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txt_TenKhuyenMai = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        pnlHoaDon = new javax.swing.JPanel();
        pnlThongTinTimKiem = new javax.swing.JPanel();
        lblTimKiem = new javax.swing.JLabel();
        lblTrangThai = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        cboTrangThai = new javax.swing.JComboBox<>();
        lblThoiGianBatDau = new javax.swing.JLabel();
        lblThoiGianKetThuc = new javax.swing.JLabel();
        lblDonGia = new javax.swing.JLabel();
        cboDonGia = new javax.swing.JComboBox<>();
        btnLoc = new javax.swing.JButton();
        txtThoiGianBatDau = new javax.swing.JTextField();
        txtThoiGianKetThuc = new javax.swing.JTextField();
        btnThoiGianBatDau = new javax.swing.JButton();
        btnThoiGianKetThuc = new javax.swing.JButton();
        pnlChucNang = new javax.swing.JPanel();
        lblSoLuongHoaDon = new javax.swing.JLabel();
        btnXemChiTiet = new javax.swing.JButton();
        btnInHoaDon = new javax.swing.JButton();
        btnExcel = new javax.swing.JButton();
        lblSLuongHoaDon = new javax.swing.JLabel();
        pnlDanhSachHoaDon = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        pnlHoaDonChiTiet = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHoaDonChiTiet = new javax.swing.JTable();

        dateDialog.setUndecorated(true);
        dateDialog.setResizable(false);

        thoiGianBatDau.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        thoiGianBatDau.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
            public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
                thoiGianBatDauOnSelectionChange(evt);
            }
        });

        javax.swing.GroupLayout dateDialogLayout = new javax.swing.GroupLayout(dateDialog.getContentPane());
        dateDialog.getContentPane().setLayout(dateDialogLayout);
        dateDialogLayout.setHorizontalGroup(
            dateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(thoiGianBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        dateDialogLayout.setVerticalGroup(
            dateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(thoiGianBatDau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        hoaDonChiTiet.getContentPane().setLayout(new java.awt.GridLayout(13, 1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Thông tin hóa đơn");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        hoaDonChiTiet.getContentPane().add(jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã hóa đơn");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 93, 30));

        txt_MaHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(txt_MaHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 8, 223, -1));

        hoaDonChiTiet.getContentPane().add(jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ngày mua hàng");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 93, 30));

        txt_NgayMuaHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(txt_NgayMuaHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 8, 223, -1));

        hoaDonChiTiet.getContentPane().add(jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tổng tiền");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 93, 30));

        txt_TongTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel5.add(txt_TongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 8, 223, -1));

        hoaDonChiTiet.getContentPane().add(jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Giá Giảm");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 93, 30));

        txt_GiaGiam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel6.add(txt_GiaGiam, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 8, 223, -1));

        hoaDonChiTiet.getContentPane().add(jPanel6);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Giá Sau giảm");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 93, 30));

        txt_GiaSauGiam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel7.add(txt_GiaSauGiam, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 8, 223, -1));

        hoaDonChiTiet.getContentPane().add(jPanel7);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Trạng thái");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 93, 30));

        txt_TrangThai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel8.add(txt_TrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 8, 223, -1));

        hoaDonChiTiet.getContentPane().add(jPanel8);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Mã nhân viên");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 93, 30));

        txt_MaNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel9.add(txt_MaNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 8, 223, -1));

        hoaDonChiTiet.getContentPane().add(jPanel9);

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Tên nhân viên");
        jPanel10.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 93, 30));

        txt_TenNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel10.add(txt_TenNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 8, 223, -1));

        hoaDonChiTiet.getContentPane().add(jPanel10);

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Tên Khách hàng");
        jPanel11.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 100, 30));

        txt_TenKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel11.add(txt_TenKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 8, 223, -1));

        hoaDonChiTiet.getContentPane().add(jPanel11);

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Số điện thoại");
        jPanel12.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 93, 30));

        txt_SoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel12.add(txt_SoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 8, 223, -1));

        hoaDonChiTiet.getContentPane().add(jPanel12);

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Mã KM");
        jPanel13.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 93, 30));

        txt_MaKhuyenMai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel13.add(txt_MaKhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 8, 223, -1));

        hoaDonChiTiet.getContentPane().add(jPanel13);

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Tên KM");
        jPanel14.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 93, 30));

        txt_TenKhuyenMai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel14.add(txt_TenKhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 8, 223, -1));

        hoaDonChiTiet.getContentPane().add(jPanel14);

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        pnlHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlHoaDon.setPreferredSize(new java.awt.Dimension(1088, 460));
        pnlHoaDon.setLayout(new java.awt.BorderLayout());

        pnlThongTinTimKiem.setBackground(new java.awt.Color(255, 255, 255));
        pnlThongTinTimKiem.setPreferredSize(new java.awt.Dimension(1078, 100));

        lblTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTimKiem.setText("Tìm kiếm: ");

        lblTrangThai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTrangThai.setText("Trạng thái: ");

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        cboTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblThoiGianBatDau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblThoiGianBatDau.setText("Thời gian: ");

        lblThoiGianKetThuc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblThoiGianKetThuc.setText("Đến: ");

        lblDonGia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDonGia.setText("Đơn giá: ");

        cboDonGia.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cboDonGia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnLoc.setText("Lọc");
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });

        txtThoiGianBatDau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtThoiGianKetThuc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnThoiGianBatDau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThoiGianBatDau.setText("jButton2");
        btnThoiGianBatDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoiGianBatDauActionPerformed(evt);
            }
        });

        btnThoiGianKetThuc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThoiGianKetThuc.setText("jButton3");
        btnThoiGianKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoiGianKetThucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlThongTinTimKiemLayout = new javax.swing.GroupLayout(pnlThongTinTimKiem);
        pnlThongTinTimKiem.setLayout(pnlThongTinTimKiemLayout);
        pnlThongTinTimKiemLayout.setHorizontalGroup(
            pnlThongTinTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinTimKiemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTinTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinTimKiemLayout.createSequentialGroup()
                        .addComponent(lblTimKiem)
                        .addGap(18, 18, 18)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlThongTinTimKiemLayout.createSequentialGroup()
                        .addComponent(lblTrangThai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(lblThoiGianBatDau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtThoiGianBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThoiGianBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblThoiGianKetThuc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtThoiGianKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThoiGianKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(lblDonGia)
                        .addGap(18, 18, 18)
                        .addComponent(cboDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlThongTinTimKiemLayout.setVerticalGroup(
            pnlThongTinTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinTimKiemLayout.createSequentialGroup()
                .addGroup(pnlThongTinTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimKiem)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(pnlThongTinTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTrangThai)
                    .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThoiGianBatDau)
                    .addComponent(lblThoiGianKetThuc)
                    .addComponent(lblDonGia)
                    .addComponent(cboDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThoiGianBatDau)
                    .addComponent(txtThoiGianKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoiGianBatDau)
                    .addComponent(btnThoiGianKetThuc))
                .addGap(25, 25, 25))
        );

        pnlHoaDon.add(pnlThongTinTimKiem, java.awt.BorderLayout.PAGE_START);

        pnlChucNang.setBackground(new java.awt.Color(255, 255, 255));
        pnlChucNang.setPreferredSize(new java.awt.Dimension(1078, 35));

        lblSoLuongHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSoLuongHoaDon.setText("Số lượng: ");

        btnXemChiTiet.setBackground(new java.awt.Color(0, 204, 255));
        btnXemChiTiet.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXemChiTiet.setText("Xem chi tiết");
        btnXemChiTiet.setPreferredSize(new java.awt.Dimension(93, 30));
        btnXemChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemChiTietActionPerformed(evt);
            }
        });

        btnInHoaDon.setBackground(new java.awt.Color(0, 204, 255));
        btnInHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInHoaDon.setText("In hóa đơn");
        btnInHoaDon.setPreferredSize(new java.awt.Dimension(93, 30));
        btnInHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInHoaDonActionPerformed(evt);
            }
        });

        btnExcel.setBackground(new java.awt.Color(0, 204, 255));
        btnExcel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcel.setText("Excel");
        btnExcel.setPreferredSize(new java.awt.Dimension(93, 30));
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        lblSLuongHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSLuongHoaDon.setText("0");

        javax.swing.GroupLayout pnlChucNangLayout = new javax.swing.GroupLayout(pnlChucNang);
        pnlChucNang.setLayout(pnlChucNangLayout);
        pnlChucNangLayout.setHorizontalGroup(
            pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSoLuongHoaDon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSLuongHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 545, Short.MAX_VALUE)
                .addComponent(btnInHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnXemChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        pnlChucNangLayout.setVerticalGroup(
            pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblSoLuongHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXemChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnInHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnExcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblSLuongHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlHoaDon.add(pnlChucNang, java.awt.BorderLayout.PAGE_END);

        pnlDanhSachHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        pnlDanhSachHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Tên khách hàng", "Mã khuyến mãi", "Ngày mua hàng", "Tổng tiền", "Giá sau giảm", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        javax.swing.GroupLayout pnlDanhSachHoaDonLayout = new javax.swing.GroupLayout(pnlDanhSachHoaDon);
        pnlDanhSachHoaDon.setLayout(pnlDanhSachHoaDonLayout);
        pnlDanhSachHoaDonLayout.setHorizontalGroup(
            pnlDanhSachHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1076, Short.MAX_VALUE)
        );
        pnlDanhSachHoaDonLayout.setVerticalGroup(
            pnlDanhSachHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDanhSachHoaDonLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pnlHoaDon.add(pnlDanhSachHoaDon, java.awt.BorderLayout.CENTER);

        jPanel1.add(pnlHoaDon);

        pnlHoaDonChiTiet.setBackground(new java.awt.Color(255, 255, 255));
        pnlHoaDonChiTiet.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa đơn chi tiết", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        pnlHoaDonChiTiet.setPreferredSize(new java.awt.Dimension(1088, 300));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        tblHoaDonChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Đơn giá", "Số lượng", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblHoaDonChiTiet);
        if (tblHoaDonChiTiet.getColumnModel().getColumnCount() > 0) {
            tblHoaDonChiTiet.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblHoaDonChiTiet.getColumnModel().getColumn(4).setPreferredWidth(70);
        }

        javax.swing.GroupLayout pnlHoaDonChiTietLayout = new javax.swing.GroupLayout(pnlHoaDonChiTiet);
        pnlHoaDonChiTiet.setLayout(pnlHoaDonChiTietLayout);
        pnlHoaDonChiTietLayout.setHorizontalGroup(
            pnlHoaDonChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHoaDonChiTietLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1066, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlHoaDonChiTietLayout.setVerticalGroup(
            pnlHoaDonChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHoaDonChiTietLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(pnlHoaDonChiTiet);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:
        index = tblHoaDon.getSelectedRow();
        String  maHD = tblHoaDon.getValueAt(index, 0).toString();
        this.filltableHDCT(repo.getAllHĐCT(maHD));
        lblSLuongHoaDon.setText(String.valueOf(tblHoaDon.getRowCount()));

    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void btnThoiGianKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoiGianKetThucActionPerformed
        // TODO add your handling code here:
        checkThoiGianTimKiem = 1;
        Point location = txtThoiGianKetThuc.getLocationOnScreen();
        int x = location.x;
        int y = location.y + txtThoiGianKetThuc.getHeight();
        dateDialog.pack();
        dateDialog.setLocation(x, y);
        dateDialog.setVisible(true);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btnThoiGianKetThucActionPerformed

    private void btnThoiGianBatDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoiGianBatDauActionPerformed
        // TODO add your handling code here:
        checkThoiGianTimKiem = 0;
        Point location = txtThoiGianBatDau.getLocationOnScreen();
        int x = location.x;
        int y = location.y + txtThoiGianBatDau.getHeight();
        dateDialog.pack();
        dateDialog.setLocation(x, y);
        dateDialog.setVisible(true);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btnThoiGianBatDauActionPerformed

    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        if (readform() != null) {
            hoaDon.locSanPham(readform());
            filltable(hoaDon.locSanPham(readform()));
            lblSLuongHoaDon.setText(String.valueOf(tblHoaDon.getRowCount()));
        }
    }//GEN-LAST:event_btnLocActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
        String s = txtTimKiem.getText().trim().toString();
        ArrayList<ModelHoaDon> list = new ArrayList<>();
        list.addAll(hoaDon.oTimKiem(s));

        if (s.isBlank()) {
            JOptionPane.showMessageDialog(jPanel1, "Thông tin tìm kiếm trống", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
        } else if (list == null || list.isEmpty()) {
            mol.setRowCount(0);
            JOptionPane.showMessageDialog(jPanel1, "Không có kết quả nào phù hợp", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            filltable(list);
            lblSLuongHoaDon.setText(String.valueOf(tblHoaDon.getRowCount()));
        }
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void thoiGianBatDauOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_thoiGianBatDauOnSelectionChange
        // TODO add your handling code here:
        if (thoiGianBatDau.getSelectedDate() == null) {
            dateDialog.setVisible(false);
        } else if (checkThoiGianTimKiem == 0) {
            Date selectedDate = thoiGianBatDau.getSelectedDate().getTime();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            txtThoiGianBatDau.setText(sdf.format(selectedDate));
        } else if (checkThoiGianTimKiem == 1) {
            Date selectedDate = thoiGianBatDau.getSelectedDate().getTime();
            SimpleDateFormat sdf = new SimpleDateFormat("yyy-MM-dd");
            txtThoiGianKetThuc.setText(sdf.format(selectedDate));
        }
    }//GEN-LAST:event_thoiGianBatDauOnSelectionChange

    private void btnXemChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemChiTietActionPerformed
        // TODO add your handling code here:
        
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn hóa đơn nào!");
            return;
        }

        String maHoaDon = tblHoaDon.getValueAt(index, 0).toString();
        ModelHoaDonInHoaDon hd = hoaDon.getChiTietHoaDon(maHoaDon);

        if (hd == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy thông tin hóa đơn!");
            return;
        }

        try {
            txt_MaHoaDon.setText(hd.getMaHoaDon() != null ? hd.getMaHoaDon() : "");
            txt_NgayMuaHang.setText(hd.getNgayMuaHang() != null ? hd.getNgayMuaHang() : "");
            txt_TongTien.setText(String.valueOf(hd.getTongTien()));
            txt_GiaGiam.setText(String.valueOf(hd.getGiaGiam()));
            txt_GiaSauGiam.setText(String.valueOf(hd.getGiaSauGiam()));
            txt_TrangThai.setText(hd.getTrangThai() != null ? (hd.getTrangThai() ? "Đã thanh toán" : "Chưa thanh toán") : "");
            txt_TenNhanVien.setText(hd.getTenNhanVien() != null ? hd.getTenNhanVien() : "");
            txt_MaNhanVien.setText(hd.getMaNhanVien() != null ? hd.getMaNhanVien() : "");
            txt_TenKhachHang.setText(hd.getTenKhachHang() != null ? hd.getTenKhachHang() : "");
            txt_SoDienThoai.setText(hd.getSdtKhachHang() != null ? hd.getSdtKhachHang() : "");
            txt_MaKhuyenMai.setText(hd.getMaKhuyenMai() != null ? hd.getMaKhuyenMai() : "");
            txt_TenKhuyenMai.setText(hd.getTenKhuyenMai() != null ? hd.getTenKhuyenMai() : "");

            hoaDonChiTiet.setSize(400, 600);
            hoaDonChiTiet.setLocationRelativeTo(this);
            hoaDonChiTiet.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi hiển thị thông tin hóa đơn!");
        }
    }//GEN-LAST:event_btnXemChiTietActionPerformed

    private void btnInHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInHoaDonActionPerformed
        // TODO add your handling code here:
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn hóa đơn nào!");
            return;
        }

        String maHoaDon = tblHoaDon.getValueAt(index, 0).toString();
        ModelHoaDonInHoaDon hd = hoaDon.getChiTietHoaDon(maHoaDon);
        ArrayList<ModelHoaDonChiTiet> listHdct = hoaDon.danhSachHoaDonChiTiet(maHoaDon);

        if (hd == null || listHdct == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy thông tin hóa đơn!");
            return;
        }

        try {
            InHoaDon1.taoHoaDon(hd, listHdct);
            JOptionPane.showMessageDialog(this, "Hóa đơn đã được in thành công!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi in hóa đơn: " + e.getMessage());
        }
    }//GEN-LAST:event_btnInHoaDonActionPerformed

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed

    }//GEN-LAST:event_btnExcelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnInHoaDon;
    private javax.swing.JButton btnLoc;
    private javax.swing.JButton btnThoiGianBatDau;
    private javax.swing.JButton btnThoiGianKetThuc;
    private javax.swing.JButton btnXemChiTiet;
    private javax.swing.JComboBox<String> cboDonGia;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JDialog dateDialog;
    private javax.swing.JDialog hoaDonChiTiet;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDonGia;
    private javax.swing.JLabel lblSLuongHoaDon;
    private javax.swing.JLabel lblSoLuongHoaDon;
    private javax.swing.JLabel lblThoiGianBatDau;
    private javax.swing.JLabel lblThoiGianKetThuc;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JPanel pnlChucNang;
    private javax.swing.JPanel pnlDanhSachHoaDon;
    private javax.swing.JPanel pnlHoaDon;
    private javax.swing.JPanel pnlHoaDonChiTiet;
    private javax.swing.JPanel pnlThongTinTimKiem;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblHoaDonChiTiet;
    private datechooser.beans.DateChooserPanel thoiGianBatDau;
    private javax.swing.JTextField txtThoiGianBatDau;
    private javax.swing.JTextField txtThoiGianKetThuc;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txt_GiaGiam;
    private javax.swing.JTextField txt_GiaSauGiam;
    private javax.swing.JTextField txt_MaHoaDon;
    private javax.swing.JTextField txt_MaKhuyenMai;
    private javax.swing.JTextField txt_MaNhanVien;
    private javax.swing.JTextField txt_NgayMuaHang;
    private javax.swing.JTextField txt_SoDienThoai;
    private javax.swing.JTextField txt_TenKhachHang;
    private javax.swing.JTextField txt_TenKhuyenMai;
    private javax.swing.JTextField txt_TenNhanVien;
    private javax.swing.JTextField txt_TongTien;
    private javax.swing.JTextField txt_TrangThai;
    // End of variables declaration//GEN-END:variables
}
